### PR TITLE
Add option to perform upgrade

### PR DESCRIPTION
**Pull request by machacekondra**
Change-Id: I8416b3d9702c87a1bc702fb55ab7c15bf486b65d
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1625915
Signed-off-by: Ondra Machacek <omachace@redhat.com>

### CODE REVIEW

**Comment by pkubica** [comment]
I don't know all the options, which user could meet during engine-setup, but you are sure that there won't be any default value which isn't configurable yet and which couldn't hurt user environment?
like: PKI renewal [ca.pem, engine.cer] (I don't know a behavior of renewing of 3rd party certificates), removing zombie tasks, modifying PostgreSQL configurations, removing old backups? (and logs?)... (I'm not sure about last two things)
if not, --accept-defaults could be there and also in z-stream upgrade.

 If are there critical questions, which should be answered knowingly by user, there shouldn't be --accept-defaults or ensure that user knows about the question and agrees with the default value. That question should be exposed also as Ansible variable with default value (if it's not too critical).
In that case, if user will not enter the variable and engine-setup will want the answer, engine-setup will fail (which is not possible with --accept-defaults parameter)

**Comment by machacekondra** [comment]
This is more question to `engine-setup` not to this role. If it's risky to use --accept-defaults` then it should be fixed by `engine-setup` to provide reasonable default.

**Comment by machacekondra** [comment]
Also in update flow there is no possible to set in answer file this optiom:

 https://github.com/oVirt/ovirt-engine/blob/436dfd8e43c3ed078d94d11e3d1a9deff2753172/packaging/setup/ovirt_engine_setup/engine_common/database.py#L1698

So we must either use `accept-defaults` or don't support upgrade.

**Comment by pkubica** [comment]
So, if there is missing option in answerfile, it's a bug on engine-setup side and it should be fixed by adding that option to answefile.

in engine-setup, the default behavior is interactive mode. You are not appending --interactive to have a choice for common options. 

I think --accept-defaults is good for user in z-stream upgrade, because there are mostly only common question (about stopping the service, proceed to upgrade, download packages...) but also there could be important question and I don't know if it could be risky or not. 
In y-stream upgrade there could be significantly more important questions and user should know about them (for example it could be one time question which will appear only when user upgrading from specific version to another). I think that what we can do for him is to expose these important questions as Ansible variables, which can have defaults. In that case, there could be --accept-defaults but with option to disable it (If user wants to be sure that he answer to all important questions, which could change his environment - to have an overview about upgrade process, not only do blind automatic upgrade)

**Comment by machacekondra** [comment]
I don't have any strong opinion on this. Since it wasn't found yet - no one used it yet. If you think we should fix it as you suggest please open a bug on engine-setup and make https://bugzilla.redhat.com/show_bug.cgi?id=1625915 as dependcy. Then we can continue with this PR.

**Pull request merged**
